name: Android CI Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Create all required secret files before the build
      - name: Create google-services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES" > ${{ github.workspace }}/app/google-services.json

      - name: Create local.properties
        run: echo "RAPIDAPI_KEY=${{ secrets.RAPIDAPI_KEY }}" > ${{ github.workspace }}/local.properties

      - name: Decode Keystore
        run: echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 --decode > ${{ github.workspace }}/app/mzansirecipes.jks

      # Build the app, passing all secrets as environment variables
      - name: Build Release Bundle
        run: ./gradlew :app:bundleRelease
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/app/mzansirecipes.jks
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Build and run unit tests
        run: ./gradlew test
